### ISSUE TITLE
Build errors in autorest examples

### ISSUE THREAD

**Issue by Posterone** [ibaca/autorest-streaming-example#2]
Hi @ibaca I wanted to try autorest but I am not able to build any of your examples. 

1.) When I try autorest-streaming-example like this: download latest zip, unzip it on my hard drive, go to root (where pom is) and do the following: 
mvn clean & mvn install I get the following error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project autorest-streaming-gwt: Fatal error compiling: invalid target release: 1.8 -> [Help 1]

2.) When I try autorest-nominatim-example, with the same steps like in 1.) I get the following error:

[ERROR] Failed to execute goal on project autorest-nominatim-api: Could not resolve dependencies for project com.intendia.gwt:autorest-nominatim-api:jar:0.1-SNAPSHOT: The following artifacts could not be resolved: com.intendia.gwt.autorest:autorest-core:jar:0.5-SNAPSHOT, com.intendia.gwt.autorest:autorest-processor:jar:0.5-SNAPSHOT: Failure to find com.intendia.gwt.autorest:autorest-core:jar:0.5-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of snapshots-repo has elapsed or updates are forced -> [Help 1]

Can you please explain what I need to do in order to test this 2 examples in simple step by step way. You wrote how to run server and the client for 1.) and I will try that when there is no build errors but for 2.) is not clear what to do. If I want to test it with gwt, what exactly I need to do ? First to start server as simple java main app and then go to gwt module root and try mvn gwt:devmode ?

Can you please check if your examples can be built and to write some more info on how to test them ?

I do not use maven and I don't like so please be so kind and put few more sentences in your readme with instructions how to build and test your examples.

Thanks in advance,

**Comment by ibaca** [comment]
Hi! you need java8 and probably a recent version of maven.
```
› mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Java version: 1.8.0_102, vendor: Oracle Corporation
```

**Comment by ibaca** [comment]
Executing the nominatim example is more tricky. It includes an android project, although it should work, I recommend that you comment out the module in the parent pom, so you don't execute nor compile it. This is an example, it actually works, but I'm pretty sure that if you are going to create an android project, you will use Gradle instead of maven. If you really want to compile the android you should be sure the android plugin for maven have everything it needs (https://github.com/simpligility/android-maven-plugin).

To execute gwt or server modules, you should use the same strategy than streaming-example (which is what you do indeed) but use java8 and maven 3.3. So `mvn gwt:devmode -am -pl :autorest-nominatim-example` for GWT and `mvn install && cd *server && mvn exec:exec` for the server. But, for the server it is much easier to just open this project in your preferred IDE and run the main class using the right click 😉.

I really need to apply Gradle instead of maven 😞.

**Comment by Posterone** [comment]
Thanks @ibaca. The main problem was my Java version in JAVA_HOME, I have several Java versions on my system and I have to switch it back and forth depending on the project.

The first (streaming) example builds and runs as explained, no problems at all.

The second  (nominatim) example did not build so I had to do some changes:

1. I commented out android module in parent pom as I will not test this out in this moment
2. I changed the version of autorest from 0.5-SNAPSHOT to 0.6
After that it builds correctly.

Starting the server was easy and as explained.
Starting the client with:  mvn gwt:devmode -am -pl :autorest-nominatim-example gives null pointer exception:

Caused by: java.lang.NullPointerException
        at net.ltgt.gwt.maven.AbstractDevModeMojo.execute(AbstractDevModeMojo.java:156)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more

Starting the client with only:  mvn gwt:devmode starts the client successfully.

I will close this issue as the build is working. Thanks again.

**Comment by ibaca** [comment]
I have changed the versioning strategy, now AutoREST always uses HEAD-SNAPSHOT, so no more old snapshot version errors! 👍 Also, I have added a profile to the nominatim example so the android module should not be included if the ANDROID_HOME env var doesn't exist.

Yep, my fault; the command `mvn gwt:devmode -am -pl :autorest-nominatim-example` should be `mvn gwt:devmode -am -pl :autorest-nominatim-gwt`, but as you discovered you can just use the command without specifying the module. The `-am -pl` is for reducing the number of compiled modules, so android and server are excluded (a bit faster).
